server:
  port: 2222

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: Temp1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       format_sql: true